# Generated by Django 3.2.4 on 2021-06-12 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Parroquia:')),
                ('tipo_parroquia', models.CharField(choices=[('urbana', 'Urbana'), ('rural', 'Rural')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Parroquias',
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Barrio o Ciudadela:')),
                ('num_viviendas', models.CharField(max_length=10, verbose_name='Número de viviendas:')),
                ('num_parques', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, verbose_name='Número de parques')),
                ('num_edificios', models.CharField(max_length=30, verbose_name='Número de edificios')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasparroquias', to='ordenamiento.parroquia')),
            ],
        ),
    ]
